name: chatbot

on:
  schedule:
    - cron: '0 6 * * 1-5' # Runs at 15:00 JST on weekdays
    - cron: '0 20 * * 0-4' # Runs at 5:00 JST on weekdays

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install line-bot-sdk
      - name: Run Japan-stock.py
        if: github.event.schedule == '0 6 * * 1-5'
        run: python Japan-stock.py
      - name: Run America-stock.py
        if: github.event.schedule == '0 20 * * 0-4'
        run: python America-stock.py
